import json
import os
from pathlib import Path

# Dicionários de equivalência
genre_equivalents = {
    "Acción": "Action",
    "Acesso Antecipado": "Early Access",
    "Aventura": "Adventure",
    "Ação": "Action",
    "Corrida": "Racing",
    "Estrategia": "Strategy",
    "Rol": "RPG",
    "Simuladores": "Simulation",
    "Strategie": "Strategy",
    "Stratégie": "Strategy",
    "Symulacje": "Simulation",
    "Анимация и моделирование": "Animation & Modeling",
    "Бесплатные": "Free To Play",
    "Дизайн и иллюстрация": "Design & Illustration",
    "Инди": "Indie",
    "Казуальные игры": "Casual",
    "Обработка фото": "Photo Editing",
    "Приключенческие игры": "Adventure",
    "Симуляторы": "Simulation",
    "Спорт": "Sports",
    "Утилиты": "Utilities",
    "Экшены": "Action",
    "冒險": "Adventure",
    "角色扮演": "RPG",
    "Abenteuer": "Adventure",
    "Accounting": "Accounting",
    "Acesso Antecipado": "Early Access",
    "Action": "Action",
    "Adventure": "Adventure",
    "Animation & Modeling": "Animation & Modeling",
    "Audio Production": "Audio Production",
    "Aventura": "Adventure",
    "Avventura": "Adventure",
    "Azione": "Action",
    "Ação": "Action",
    "Carreras": "Racing",
    "Casual": "Casual",
    "Corrida": "Racing",
    "Deportes": "Sports",
    "Design & Illustration": "Design & Illustration",
    "Early Access": "Early Access",
    "Education": "Education",
    "Eventyr": "Adventure",
    "Free To Play": "Free-to-Play",
    "Free-to-Play": "Free-to-Play",
    "Game Development": "Game Development",
    "Gelegenheitsspiele": "Casual",
    "Gore": "Gore",
    "Indie": "Indie",
    "Massively Multiplayer": "Massively Multiplayer",
    "Multigiocatore di massa": "Massively Multiplayer",
    "Nudity": "Nudity",
    "Photo Editing": "Photo Editing",
    "RPG": "RPG",
    "Racing": "Racing",
    "Sexual Content": "Sexual Content",
    "Simuladores": "Simulation",
    "Simulation": "Simulation",
    "Simulazione": "Simulation",
    "Simulação": "Simulation",
    "Software Training": "Software Training",
    "Sports": "Sports",
    "Strategy": "Strategy",
    "Utilities": "Utilities",
    "Video Production": "Video Production",
    "Violent": "Violent",
    "Web Publishing": "Web Publishing",
    "Гонки": "Racing",
    "Инди": "Indie",
    "Приключенческие игры": "Adventure",
    "Ролевые игры": "RPG",
    "Симуляторы": "Simulation",
    "Спорт": "Sports",
    "Экшены": "Action",
    "アクション": "Action",
    "アドベンチャー": "Adventure",
    "アニメーション & モデリング": "Animation & Modeling",
    "インディー": "Indie",
    "デザイン & イラストレーション": "Design & Illustration"
}

category_equivalents = {
    "Cartes à échanger Steam": "Steam Trading Cards",
    "Classificações Steam": "Steam Ratings",
    "Compartilhamento em família": "Family Sharing",
    "Compat. contrôleurs complète": "Full Controller Support",
    "Compat. contrôleurs partielle": "Partial Controller Support",
    "Compat. parcial com controle": "Partial Controller Support",
    "Compat. parcial con control": "Partial Controller Support",
    "Compat. parcial con mando": "Partial Controller Support",
    "Compat. total com controle": "Full Controller Support",
    "Compatíveis com RV": "VR Supported",
    "Compras dentro de la aplicación": "In-App Purchases",
    "Conquistas Steam": "Steam Achievements",
    "Cooperativo": "Co-op",
    "Cooperativo on-line": "Online Co-op",
    "Cromos de Steam": "Steam Trading Cards",
    "Estadísticas": "Stats",
    "Estatísticas": "Stats",
    "HDR disponible": "HDR available",
    "JcJ en ligne": "Online PvP",
    "Jednoosobowa": "Single-player",
    "JxJ": "PvP",
    "JxJ on-line": "Online PvP",
    "JxJ tela dividida/compart.": "Shared/Split Screen PvP",
    "Karty kolekcjonerskie Steam": "Steam Trading Cards",
    "Logros de Steam": "Steam Achievements",
    "Multijogador": "Multi-player",
    "Multijoueur": "Multi-player",
    "Multijoueur multiplateforme": "Cross-Platform Multiplayer",
    "Nuvem Steam": "Steam Cloud",
    "Osiągnięcia Steam": "Steam Achievements",
    "Partage familial": "Family Sharing",
    "Partilha de Biblioteca": "Family Sharing",
    "Préstamo familiar": "Family Sharing",
    "PvP online": "Online PvP",
    "Remote Play para tabletas": "Remote Play on Tablet",
    "Remote Play sur tablette": "Remote Play on Tablet",
    "Remote Play sur téléphone": "Remote Play on Phone",
    "Remote Play sur télévision": "Remote Play on TV",
    "Remote Play на планшете": "Remote Play on Tablet",
    "Remote Play на телевизоре": "Remote Play on TV",
    "Remote Play на телефоне": "Remote Play on Phone",
    "Solo": "Single-player",
    "Steam 成就": "Steam Achievements",
    "Steam 雲端": "Steam Cloud",
    "Subtítulos disponibles": "Captions available",
    "Succès Steam": "Steam Achievements",
    "Tablas de clasificación de Steam": "Steam Leaderboards",
    "Tarjetas de Steam": "Steam Trading Cards",
    "Udostępnianie gier": "Family Sharing",
    "Um jogador": "Single-player",
    "Un jugador": "Single-player",
    "Warsztat Steam": "Steam Workshop",
    "Wieloosobowa": "Multi-player",
    "Wieloplatformowa wieloosobowa": "Cross-Platform Multiplayer",
    "Workshop Steam": "Steam Workshop",
    "Внутриигровые покупки": "In-App Purchases",
    "Для нескольких игроков": "Multi-player",
    "Для одного игрока": "Single-player",
    "Достижения Steam": "Steam Achievements",
    "Игрок против игрока": "PvP",
    "Игрок против игрока (общий/разделённый экран)": "Shared/Split Screen PvP",
    "Игрок против игрока (по сети)": "Online PvP",
    "Коллекционные карточки Steam": "Steam Trading Cards",
    "Кооператив": "Co-op",
    "Кооператив (общий/разделённый экран)": "Shared/Split Screen Co-op",
    "Кооператив (по сети)": "Online Co-op",
    "Мастерская Steam": "Steam Workshop",
    "Общий/разделённый экран": "Shared/Split Screen",
    "Полная поддержка контроллеров": "Full Controller Support",
    "С редактором уровней": "Includes level editor",
    "Семейный доступ": "Family Sharing",
    "Скрытые субтитры": "Captions available",
    "Таблицы лидеров Steam": "Steam Leaderboards",
    "Частичная поддержка контроллеров": "Partial Controller Support",
    "單人": "Single-player",
    "完全支援控制器": "Full Controller Support",
    "親友同享": "Family Sharing",
        "Achievement di Steam": "Steam Achievements",
    "Acquisti dall'applicazione": "In-App Purchases",
    "Adjustable Difficulty": "Adjustable Difficulty",
    "Adjustable Text Size": "Adjustable Text Size",
    "Alternativas de cores": "Color Alternatives",
    "Camera Comfort": "Camera Comfort",
    "Captions available": "Captions available",
    "Cartas Colecionáveis Steam": "Steam Trading Cards",
    "Carte collezionabili di Steam": "Steam Trading Cards",
    "Chat Speech-to-text": "Chat Speech-to-text",
    "Chat Text-to-speech": "Chat Text-to-speech",
    "Classificações Steam": "Steam Leaderboards",
    "Co-op": "Co-op",
    "Co-op – delt/opdelt skærm": "Shared/Split Screen Co-op",
    "Color Alternatives": "Color Alternatives",
    "Commentary available": "Commentary available",
    "Compartilhamento em família": "Family Sharing",
    "Compat. parcial con mando": "Partial Controller Support",
    "Compat. total com controle": "Full controller support",
    "Compatibile con VR": "VR Support",
    "Compatible con RV": "VR Support",
    "Condivisione familiare": "Family Sharing",
    "Conquistas Steam": "Steam Achievements",
    "Controles de volume independentes": "Custom Volume Controls",
    "Coop. tela dividida/compart.": "Shared/Split Screen Co-op",
    "Cooperativo": "Co-op",
    "Cooperativo on-line": "Online Co-op",
    "Cross-Platform Multiplayer": "Cross-Platform Multiplayer",
    "Custom Volume Controls": "Custom Volume Controls",
    "Einzelspieler": "Single-player",
    "Estatísticas": "Stats",
    "Familiedeling": "Family Sharing",
    "Familienbibliothek": "Family Sharing",
    "Family Sharing": "Family Sharing",
    "Fuld controllerunderstøttelse": "Full controller support",
    "Full controller support": "Full controller support",
    "Geteilter Bildschirm": "Shared/Split Screen",
    "Giocatore singolo": "Single-player",
    "HDR available": "HDR available",
    "In-App Purchases": "In-App Purchases",
    "Includes Source SDK": "Includes Source SDK",
    "Includes level editor": "Includes level editor",
    "Incluye editor de niveles": "Includes level editor",
    "JcJ": "PvP",
    "JcJ en línea": "Online PvP",
    "JxJ": "PvP",
    "JxJ on-line": "Online PvP",
    "JxJ tela dividida/compart.": "Shared/Split Screen PvP",
    "Keyboard Only Option": "Keyboard Only Option",
    "Koop": "Co-op",
    "Koop-Spiele mit geteiltem Bildschirm": "Shared/Split Screen Co-op",
    "LAN Co-op": "LAN Co-op",
    "LAN PvP": "LAN PvP",
    "Logros de Steam": "Steam Achievements",
    "MMO": "MMO",
    "Mehrspieler": "Multiplayer",
    "Mouse Only Option": "Mouse Only Option",
    "Multi-player": "Multiplayer",
    "Multigiocatore": "Multiplayer",
    "Multigiocatore multipiattaforma": "Cross-Platform Multiplayer",
    "Multijogador": "Multiplayer",
    "Multijugador": "Multiplayer",
    "Multiplayer": "Multiplayer",
    "Narrated Game Menus": "Narrated Game Menus",
    "Nuvem Steam": "Steam Cloud",
    "Online Co-op": "Online Co-op",
    "Online PvP": "Online PvP",
    "Opção apenas com teclado": "Keyboard Only Option",
    "Partial Controller Support": "Partial Controller Support",
    "Partita cooperativa online": "Online Co-op",
    "Playable without Timed Input": "Playable without Timed Input",
    "Préstamo familiar": "Family Sharing",
    "PvP": "PvP",
    "PvP online": "Online PvP",
    "Remote Play Together": "Remote Play Together",
    "Remote Play auf Smartphones": "Remote Play on Phone",
    "Remote Play auf Tablets": "Remote Play on Tablet",
    "Remote Play na TV": "Remote Play on TV",
    "Remote Play no celular": "Remote Play on Phone",
    "Remote Play no tablet": "Remote Play on Tablet",
    "Remote Play on Phone": "Remote Play on Phone",
    "Remote Play on TV": "Remote Play on TV",
    "Remote Play on Tablet": "Remote Play on Tablet",
    "Remote Play sul tablet": "Remote Play on Tablet",
    "Remote Play sul telefono": "Remote Play on Phone",
    "Remote Play на телевизоре": "Remote Play on TV",
    "Save Anytime": "Save Anytime",
    "Shared/Split Screen": "Shared/Split Screen",
    "Shared/Split Screen Co-op": "Shared/Split Screen Co-op",
    "Shared/Split Screen PvP": "Shared/Split Screen PvP",
    "Single-player": "Single-player",
    "Singleplayer": "Single-player",
    "Som estéreo": "Stereo Sound",
    "Stats": "Stats",
    "Steam Achievements": "Steam Achievements",
    "Steam Cloud": "Steam Cloud",
    "Steam Leaderboards": "Steam Leaderboards",
    "Steam Timeline": "Steam Timeline",
    "Steam Trading Cards": "Steam Trading Cards",
    "Steam Turn Notifications": "Steam Turn Notifications",
    "Steam Workshop": "Steam Workshop",
    "Steam-Errungenschaften": "Steam Achievements",
    "Steam-præstationer": "Steam Achievements",
    "SteamVR Collectibles": "SteamVR Collectibles",
    "Steamクラウド": "Steam Cloud",
    "Steamトレーディングカード": "Steam Trading Cards",
    "Steamランキング": "Steam Leaderboards",
    "Steamワークショップ": "Steam Workshop",
    "Steam実績": "Steam Achievements",
    "Stereo Sound": "Stereo Sound",
    "Subtitle Options": "Subtitle Options",
    "Supporto completo per i controller": "Full controller support",
    "Supporto parziale per i controller": "Partial Controller Support",
    "Surround Sound": "Surround Sound",
    "Tablas de clasificación de Steam": "Steam Leaderboards",
    "Touch Only Option": "Touch Only Option",
    "Tracked Controller Support": "Tracked Controller Support",
    "Um jogador": "Single-player",
    "Un jugador": "Single-player",
    "Usa Valve Antitrapaça": "Valve Anti-Cheat enabled",
    "VR Only": "VR Only",
    "VR Support": "VR Support",
    "VR Supported": "VR Support",
    "Valve Anti-Cheat enabled": "Valve Anti-Cheat enabled",
    "Valve Anti-Cheat integriert": "Valve Anti-Cheat enabled",
    "Volle Controllerunterstützung": "Full controller support",
    "Для нескольких игроков": "Multiplayer",
    "Для одного игрока": "Single-player",
    "Достижения Steam": "Steam Achievements",
    "Игрок против игрока": "PvP",
    "Игрок против игрока (локальная сеть)": "LAN PvP",
    "Игрок против игрока (общий/разделённый экран)": "Shared/Split Screen PvP",
    "Игрок против игрока (по сети)": "Online PvP",
    "Коллекционные карточки Steam": "Steam Trading Cards",
    "Кооператив": "Co-op",
    "Кооператив (локальная сеть)": "LAN Co-op",
    "Кооператив (общий/разделённый экран)": "Shared/Split Screen Co-op",
    "Кооператив (по сети)": "Online Co-op",
    "Кросс-платформенный мультиплеер": "Cross-Platform Multiplayer",
    "Мастерская Steam": "Steam Workshop",
    "Общий/разделённый экран": "Shared/Split Screen",
    "Поддержка VR": "VR Support",
    "Поддержка отслеживания контроллеров": "Tracked Controller Support",
    "Полная поддержка контроллеров": "Full controller support",
    "С редактором уровней": "Includes level editor",
    "Семейный доступ": "Family Sharing",
    "Таблицы лидеров Steam": "Steam Leaderboards",
    "Частичная поддержка контроллеров": "Partial Controller Support",
    "シングルプレイヤー": "Single-player",
    "ファミリーシェアリング": "Family Sharing"
}

# Funções auxiliares
def normalize_str(s):
    return s.strip() if isinstance(s, str) else ""

def apply_equivalents(lst, eq_map):
    descriptions = []
    for dict in lst:
        desc = dict['description']
        mapped_desc = eq_map.get(desc, desc)
        temp_dict = {
            'description' : mapped_desc,
            'id' : dict['id']
        }
        descriptions.append(temp_dict)
    
    return descriptions

def normalize_dataset():
    input_path = "filtered_datasets/filtered_dataset.json"
    output_path = "filtered_datasets/normalized_filtered_dataset.json"
    
    # Verify input file exists
    if not os.path.exists(input_path):
        print(f"Arquivo de entrada não encontrado: {input_path}")
        return
    
    # Load data from JSON
    with open(input_path, 'r', encoding='utf-8') as f:
        games = json.load(f)
    
    # Apply normalization
    for game in games.values():
        if "genres" in game:
            game["genres"] = apply_equivalents(game["genres"], genre_equivalents)
        if "categories" in game:
            game["categories"] = apply_equivalents(game["categories"], category_equivalents)
        if "developers" in game:
            game["developers"] = [normalize_str(d) for d in game["developers"] if isinstance(d, str)]
        if "publishers" in game:
            game["publishers"] = [normalize_str(p) for p in game["publishers"] if isinstance(p, str)]
    
    # Create output directory if needed
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    # Save as JSON
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(games, f, ensure_ascii=False, indent=2)
    
    print(f"Arquivo processado e salvo em: {output_path}")

if __name__ == '__main__':
    normalize_dataset()